### ISSUE TITLE
Is there still a way to convert from OXC parsed AST to Ezno? 

### ISSUE THREAD

**Issue by andymac4182** [kaleidawave/ezno#116]
Hi,

I am using oxc for another part of the project I am working on but would love to use some of the type synthasis that you have. I was wondering if this line is still valid but I just can't find the right place? 
> See [oxc_type_synthesis](https://github.com/web-infra-dev/oxc) for similar code that connects the logic with OXCs AST.

Cheers

**Comment by kaleidawave** [comment]
There was a crate which ran Ezno's type checking API over Oxc's AST. But unfortunately for a few reasons it has been removed https://github.com/oxc-project/oxc/pull/2048. 

Maybe it will come back in the future (as I still have the code) when the type checker is ready to be used in existing projects and the crate can stay updated, but currently the only way to run the checker is using the Ezno toolchain with its own parser.
