### ISSUE TITLE
`never` type lookup - "Cannot find type never"

### ISSUE THREAD

**Issue by CharlesTaylor7** [kaleidawave/ezno#136]
```ts
function loops(): never {
    while (true);
}

loops() satisfies never
```

When I check this block of code I get an error of  "Cannot find type never".

I suspect this is an issue at the parsing stage, because there is already code in the subtyping logic that checks for the `never` type.

**Comment by CharlesTaylor7** [comment]
@kaleidawave I started a branch for `never` related issues. It's necessary to get `Pick`, `Omit`, `Exclude` and `Extract` utility types to work properly.
https://github.com/CharlesTaylor7/ezno/tree/never-type

Also, confirmed that tsc does enough reachability analysis to verify the return type of an infinite loop is `never`, instead of `void`.
https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAGznADgZwBQEoBciYApgG7EBOiA3gFCIOIDuAFjMsYtlBSMbgG5aAX1q1UGHLkSYAhrEzAYxTETKVaQA

**Comment by CharlesTaylor7** [comment]
@kaleidawave It's an interesting question you posed about shadowing `never` with another type. I've never tried to do that before, so I checked in TS playground. Apparently certain types are treated like keywords and cannot be shadowed.  

https://www.typescriptlang.org/play?#code/C4TwDgpgBAdhBuEBOUC8UCsBuAUAMwFcYBjYASwHsYAeORJAPgAo8KKAuWBZASigG8cOAL5DQkKAGdgSMjADmaKABZchEuSrVpshc1YcpMufL6CRQA

**Comment by kaleidawave** [comment]
Interesting. That's actually quite a good idea. I could see having a type parameter named `never` could cause a lot of a confusion. 

So your addition to the type annotation name lookup is correct and my suggestion about the `Root` context named typed would create diverging behaviour with TSC. 

I think type shadowing works ATM (although it seems I have added any tests for it). Adding prevention and emitting of errors around invalid type aliases and type parameter names needs adding.
