### ISSUE TITLE
Simple example of typechecking from code?

### ISSUE THREAD

**Issue by jloganolson** [kaleidawave/ezno#162]
Do you have an example of how I could run type checking on a string or file of typescript from within code?

I tried 
```ts
import {check} from 'ezno/initialised'
const fs_handler = (_path) => "const x = !t ? 4 : 5;";
console.dir(check("input.js", fs_handler), { depth: 5 })
```

It ran, but didn't seem to produce the desired output. I've been looking for awhile so figure i'd just ask.

**Comment by kaleidawave** [comment]
Yep you should be able to use the JS (via WASM) version of the checker with

```ts
import {check} from 'ezno/initialised';
const fs_handler = (_path) => "const x: string = t ? 4 : 5;";
const output = check("input.ts", fs_handler);
console.log(output.diagnostics);
```

Since the addition of the playground #115, `check` also returns a lookup table for getting the type name of expressions at a position, thus `.diagnostics` is needed.

**Comment by kaleidawave** [comment]
Ah yes I see there is outdated documentation (and `check` is missing) of this. Will update 

https://github.com/kaleidawave/ezno/blob/aafc9a4bfefe72f43de89976ff56542711759081/src/js-cli-and-library/README.md?plain=1#L15-L37

**Comment by kaleidawave** [comment]
I also wonder if there a way to make the `console.log` more informative...?

![image](https://github.com/kaleidawave/ezno/assets/26967284/0b70afc3-5c74-43aa-a5d7-fbda63270772)

**Comment by jloganolson** [comment]
Yeah, is there something i can do to that WASMCheckOutput to actually see/log typecheck errors (or that it passes)

**Comment by kaleidawave** [comment]
Yep `.diagnostics` contains type checker errors with reasons and there *byte* origin position in the source.

![image](https://github.com/kaleidawave/ezno/assets/26967284/3ea5ff7f-f3ff-4447-b5ae-4ef87ec582ec)

It also contains information and warnings. So you might want to filter on `.kind`.

Have updated in the documentation in #155
