### ISSUE TITLE
Error on hashbang

### ISSUE THREAD

**Issue by rotu** [kaleidawave/ezno#176]
ezno does not tolerate Hashbang Comments.
```js
#!/usr/bin/env node

console.log("hello")
```

These are permitted at the beginning of a script as of ECMAScript 2023
https://262.ecma-international.org/15.0/index.html#sec-hashbang

```
error: 
  ┌─ ./my/script.js:1:2
  │
1 │ #!/usr/bin/env node
  │  ^^ Expected identifier at private in expression, found LogicalNot
```

**Comment by kaleidawave** [comment]
Ah yes, I remember seeing them added now. Should not be too hard to implement if `#!` is treated in the similar way to the `//` sequence. 

Wondering where this hashbang comment can exist? Is it just at the start of file, or any statement position? 

aka is the following valid?
```js
const x = 2;
#!/usr/bin/env node
const y = 2;
```

Will have to check the specification

**Comment by rotu** [comment]
Just at the beginning
