### ISSUE TITLE
Assigning to field with a union type across functions

### ISSUE THREAD

**Issue by xbgnx** [kaleidawave/ezno#18]
Where I can try Ezno? Please add some online sandbox where I can try Ezne online
Here is interesting example that makes you think about whole soundness of type checking
```
function anotherFunc<T extends {field: string | null}>(obj: T){
    obj.field = null;
};

function someFunc<T extends {field: string}>(obj: T){
    obj.field;
    anotherFunc(obj);
    obj.field.length;
};
```
Does Ezno handle error in this example?  (TypeScript doesn't). Here we have a runtime error because caller sets "obj.field = null" but callee does not expect this value. I think typecheker needs to calculate diff between passed type and type declared in parameter signature and make sure nothing from this diff set of values does not assign to parameter in the body of function in order to prevent runtime error. What do you think?

**Comment by kaleidawave** [comment]
> Where I can try Ezno? Please add some online sandbox where I can try Ezne online

Currently not public, will be by the summer hopefully.

> Here is interesting example that makes you think about whole soundness of type checking

Yes this is an interesting issue that is really important for type safety. Under the type rules (which follow TypeScript), it is valid to pass `obj` to `anotherFunc`. And while this passes under the rules of TypeScript it will throw at runtime as there is no property `.length` on null.

Haven't tested but it all the data should be present as Ezno **does** track mutation effects. I think it would throw a *property does not exist* on the `obj.field.length` line.

**Comment by kaleidawave** [comment]
Interestingly this is solved in Flow because they do not accept passing a general type to a union type. 

https://flow.org/try/#1N4Igxg9gdgZglgcxALmAXwDTggEwKYogwCuUYALnNAAQCGUE5AFngE4BipYAPACrXJqweHgA2OQQGdyrOFATUAPtSjFRotAD4AFBABGAK0G8AlMAA6UateoB6W9X0GAdCPHUAvCrWiA3JZtqSChJCFE8Z1EIBG1zECY4OJNLNH8oSxIyShpQgFs8TjI+ASE3CWppWXktXUNjMwCbJ1c4MRw0wPpGFg4uWoMTDqbDFrbIvHlmNNSQLAA3NkkqKEI5gAZnACY1zecARhA0IA

I don't like this behaviour and diverges from TS. So effects are the way to go here

**Comment by kaleidawave** [comment]
This sort of works. Given

```ts
const x = { a: 2 }
function updateA(obj: { a: string | number }) {
    obj.a = "hi"
}
updateA(x)
const y: number = x.a
```

It errors with `Type "hi" is not assignable to type number`. See [specification.md#updating-property](https://github.com/kaleidawave/ezno/blob/main/checker/specification/specification.md#updating-property)

Need to test with arrays and currently doesn't respect if `x` has an assingment restriction, so not perfect yet

**Comment by kaleidawave** [comment]
I think this is solved both through

**Comment by kaleidawave** [comment]
I think this is now solved with

https://github.com/kaleidawave/ezno/blob/0881454c9de4579273d4941f8af29c33f99af34c/checker/specification/specification.md#assignment-to-union

and 

https://github.com/kaleidawave/ezno/blob/0881454c9de4579273d4941f8af29c33f99af34c/checker/specification/specification.md#mutating-an-object-by-a-function

Might come back to make more user friendly and double check all the edge cases are identified at some point, but for now it is at least identified 🎉
