### ISSUE TITLE
Add regex checking

### ISSUE THREAD

**Issue by kaleidawave** [kaleidawave/ezno#183]
Want a few things

- Parsing to get the groups so that `match.groups` is strongly typed
- Validating a regex?
- Maybe regex methods could be constant functions that can be evaluated at compile time?

Maybe use a external library? Needs to be ecmascript compliant

**Comment by lemueldls** [comment]
I know of [regress](https://lib.rs/crates/regress) because Boa JS uses it.

**Comment by kaleidawave** [comment]
Whoops duplicate of #175, I thought I remembered writing something like this. #175 now has the word "regex" in the title so that I can find it better
