### ISSUE TITLE
Template literal type printing

### ISSUE THREAD

**Issue by kaleidawave** [kaleidawave/ezno#188]
At the moment the template literal **type** `` `Hi${string}` `` is printed at `string` (as that is its base type).

There should be special logic to pick up the type `Constructor::BinaryOperation { lhs, rhs, operation: MathematicalAndBitwise::Addition }` and then form a chain of `parts: Vec<(String, TypeId)>, trailing: String` using recursive type traversal. If it looks like a template literal type (aka no number + number) then it can be printed like on (see example in parser)

It should be added around here

https://github.com/kaleidawave/ezno/blob/e6f6ffd7cb48285cdaaf7e57e4d636bbaf038b03/checker/src/types/printing.rs#L254-L281

**Comment by sor4chi** [comment]
Hello @kaleidawave, next I am working on this.

https://github.com/kaleidawave/ezno/blob/d67cd1b0b9f5c308a8d3f8ea04c5ccb8baa470c5/checker/specification/specification.md#L4079-L4094

When implementing type expansion in template literals, this case fails, but how far do you expect to expand?

```
// Current
No property 'property_b' on { [string]: X[keyof X & string] }

// Option 1
No property 'property_b' on { [`property_${P}`]: X[keyof X & string] }

// Option 2
No property 'property_b' on { [`property_${((keyof T) & string)}`]: X[keyof X & string] }

// Option 3
No property 'property_b' on { [`property_${((keyof X) & string)}`]: X[keyof X & string] }
```

**Comment by kaleidawave** [comment]
Awesome! Yes I like option 3 as it has the most information. (is there any difference between 2 and 3?). It is fine to modify the specification if it is just a printing difference etc.

**Comment by sor4chi** [comment]
It is simply a question of how deep to search, so if Option 3 is fine, this seems to be the way to go!

Incidentally, this is how this case currently works, but it is also supposed to be deployed, right?


```ts
const invalidStr: `Hi${string}` = 'Hello, there!';
type InvalidStr = `Hi${string}`;
const invalidStr2: InvalidStr = 'Hello, there2!';
```

- Type "Hello, there!" is not assignable to type `Hi${string}`
- Type "Hello, there2!" is not assignable to type InvalidStr

**Comment by kaleidawave** [comment]
Yep I think that is fine. I am split on whether to print the name vs the value of an alias. I think it currently easiest to just print the name.

**Comment by sor4chi** [comment]
OK, so I'm going to Open the PR as it is for now!
