### ISSUE TITLE
Allow type-only import labels

### ISSUE THREAD

**Issue by noahbald** [kaleidawave/ezno#194]
Hi, just playing around with this - I've noticed that checking type only imports seems to result in an error.
This isn't mentioned in the specification docs, so perhaps it was missed?

```txt
error:
  ┌─ ./src/actions/address.ts:4:15
  │
4 │ import { type PartialMessage } from "@bufbuild/protobuf";
  │               ^^^^^^^^^^^^^^ Expected CloseBrace or Comma found Identifier("PartialMessage")
```

**Comment by kaleidawave** [comment]
Yep, seems to be a parser issue. I think I added support for `type` keyword in the import *part* recently

https://github.com/kaleidawave/ezno/blame/main/parser/src/declarations/mod.rs#L394

and yes doesn't appear to be a test for it in `specification.md`. Will take a look at it. I know I added  `import type ... from ...` but I don't think the checker currently checks simple item type modifiers.

**Comment by kaleidawave** [comment]
I believe the parsing for this has now been fixed a while back.  https://kaleidawave.github.io/ezno/playground/?id=31vj7m

Will tag #185 to look at whether this works in the type checker.
