### ISSUE TITLE
Generic names leak out of functions

### ISSUE THREAD

**Issue by kaleidawave** [kaleidawave/ezno#196]
Somehow type parameter `YEA` has its name declared in the main scope (not the function scope)

```ts	
function x<YEA>() {}

type B = YEA;
```

This might have to do with the hoisting (`synthesise_shape`)

**Comment by sor4chi** [comment]
Hello, I investigated this issue!

It seems that in the `hoist_statements` function, specifically in the Function match section, `synthesise_shape` is applied to the environment outside the function scope without generating a new lexical scope within the function. As a result, it might be registering to the `named_types` in the scope one level higher than intended.


https://github.com/kaleidawave/ezno/blob/d67cd1b0b9f5c308a8d3f8ea04c5ccb8baa470c5/checker/src/synthesis/hoisting.rs#L559-L568

What do you think?

**Comment by kaleidawave** [comment]
Yes, I think this is the issue. Btw `synthesis_shape` is hoisting the function type with its value parameter types and type parameters (type parameter names are the ones leaking).

The stages for *checking* (filtered for functions) 
1. `synthesis_shape` type annotations on a function
2. `synthesis_function` body of a function
3. *run statements*

I think you are correct, the same environment is used for `synthesis_type_parameter` 

https://github.com/kaleidawave/ezno/blob/d67cd1b0b9f5c308a8d3f8ea04c5ccb8baa470c5/checker/src/synthesis/functions.rs#L636-L641

I think it needs to be modified to do a similar process to function type annotations where it creates a new lexical environment and does the synthesis inside.

https://github.com/kaleidawave/ezno/blob/d67cd1b0b9f5c308a8d3f8ea04c5ccb8baa470c5/checker/src/synthesis/functions.rs#L597-L602

Would you be interesting in committing and adding a test for the fix?

**Comment by sor4chi** [comment]
Thank you! Of course, I'll try.
