### ISSUE TITLE
Add a LSP (language service protocol) extension

### ISSUE THREAD

**Issue by kaleidawave** [kaleidawave/ezno#22]
*need to update the 2k lines of code I wrote last year to the new Ezno*

[There is an example video near the top of the page](https://kaleidawave.github.io/posts/introducing-ezno)

Things to consider:
- AST has to be partially valid, this may only work for `ezno-parser` as it has [Cursor](https://docs.rs/ezno-parser/0.0.3/ezno_parser/expressions/enum.Expression.html#variant.Cursor) variants which enable `const x = ;` to be valid AST 
- Distribution using WASM seems like a good solution: https://www.osohq.com/post/building-vs-code-extension-with-rust-wasm-typescript
- What features of https://microsoft.github.io/language-server-protocol/ to support

Future things
- Not rechecking the whole source every write

**Comment by kaleidawave** [comment]
This probably won't happen this year as I don't think it is particularly useful while the checker is still in demo stages.

Maybe I will release the LSP I build last year but it will likely only be for sponsors to test and only print diagnostics without completions etc...

Or this feature gets added if Oxc gets a vscode extension? 👀  https://github.com/web-infra-dev/oxc/issues/688

**Comment by Boshen** [comment]
We have the code here https://github.com/web-infra-dev/oxc/tree/main/editor/vscode

Need to find the time to publish this thing :-/

**Comment by kaleidawave** [comment]
A basic LSP is now available to GitHub sponsors. It is similar to the [web playground](https://kaleidawave.github.io/ezno/playground/) but works locally (in vscode) and can support multiple files & imports etc. Similar to the checker it is WIP & not production ready. It will be available only to sponsors for the foreseeable future.

If you have contributed code to this repository and want access then LMK and I can add you to the private repository!
