### ISSUE TITLE
Improve and fix parser fuzzing

### ISSUE THREAD

**Issue by kaleidawave** [kaleidawave/ezno#28]
The two fuzzing tests are current failing

The `module_roundtrip_naive` is currently catching a issue in [TemplateLiteral](https://github.com/kaleidawave/ezno/blob/d07ae8bfef9fedfa1eb629a33ea374ac141208ac/parser/src/expressions/template_literal.rs#L140). [This is great as it highlights where the invalid assertion is, but currently it only shows the following](https://github.com/kaleidawave/ezno/actions/runs/5247449724/jobs/9477654647#step:7:293)

```shell
Failing input:

	artifacts/module_roundtrip_naive/crash-b858cb282617fb0956d960215c8e84d1ccf909c6

Output of `std::fmt::Debug`:

	" "

Reproduce with:

	cargo fuzz run --sanitizer=none module_roundtrip_naive artifacts/module_roundtrip_naive/crash-b858cb282617fb0956d960215c8e84d1ccf909c6

Minimize test case with:

	cargo fuzz tmin --sanitizer=none module_roundtrip_naive artifacts/module_roundtrip_naive/crash-b858cb282617fb0956d960215c8e84d1ccf909c6
```

Is this identifier `b858cb282617fb0956d960215c8e84d1ccf909c6` deterministic and able to be used locally, or is it lost after the run? If not it would be great if it was printed afterwards or else uploaded using [upload-artifact](https://github.com/actions/upload-artifact) (the 90 day retention is fine), so that the input is can be used to help fix the issue.

---

And the second fuzzing suite, `module_roundtrip_structured`, currently [cannot find `arbitrary`](https://github.com/kaleidawave/ezno/actions/runs/5247449724/jobs/9477654813#step:7:251). I think maybe a dependency changed in `boa-ast` (which we are currently use as a agent for generating AST)?

**Comment by kaleidawave** [comment]
Eventually would be great to see the structured parsing fuzzing tests replicated for the type checker, but worth waiting a few months until the checker gets more basic functionality!

**Comment by addisoncrump** [comment]
So, the failing test case *is* being printed: it's just a space!

As for the structured: yup, it needs the `arbitrary` dependency. I can do that change fairly quick :slightly_smiling_face:

**Comment by addisoncrump** [comment]
> Eventually would be great to see the structured parsing fuzzing tests replicated for the type checker, but worth waiting a few months until the checker gets more basic functionality!

This is a very hard problem that is [still under active research](https://www.fuzzingbook.org/html/FuzzingWithConstraints.html). The issue is that generating usages of symbols that are representative of scenarios that trigger various functionality in a type checker is _extremely hard_. It's certainly possible, but a fuzzer will not be nearly as useful here as a formal verification tool.

**Comment by jasikpark** [comment]
I'm very curious if it would be possible to generate inputs [metamorphically](https://www.doc.ic.ac.uk/~afd/homepages/papers/pdfs/2021/MET.pdf), to start from a simple tautology, like `true extends true` and to assert that it should hold for any replacements that increase the size of that expression.

So we could build up a series of https://github.com/returntocorp/semgrep replacements that *should* result in the same type to fuzz the resulting effective type?

**Comment by jasikpark** [comment]
See if https://www.richard-towers.com/2023/03/11/typescripting-the-technical-interview.html typechecks :)

**Comment by kaleidawave** [comment]
> This is a very hard problem that is [still under active research](https://www.fuzzingbook.org/html/FuzzingWithConstraints.html). The issue is that generating usages of symbols that are representative of scenarios that trigger various functionality in a type checker is _extremely hard_. It's certainly possible, but a fuzzer will not be nearly as useful here as a formal verification tool.

That is really interesting! I see, random programs can expose a lot of parsing logic but not as much checking logic.

A test which checks random programs and checking that it doesn't panic would still be useful eventually.

Or a harder project: after checking run the input through a JS interpreter and checking that it lines up with the checker results. But something for the future 😉
