### ISSUE TITLE
Add positions to events

### ISSUE THREAD

**Issue by kaleidawave** [kaleidawave/ezno#37]
When a function returned value (which is looked up via events) doesn't match it error. This error doesn't contain the location of the return.

Many of the `Event`s could benefit from having a position (using `SourceWithSpan`) to mark where they occurred. 

To do this add a field with the type `SourceWithSpan` to an event and modify the synthesis and other code to make it compile. Then repeat for every variant of `Event`

**Comment by kaleidawave** [comment]
Hey @NitantP, thanks for the interest. Hopefully the following answers your questions

1. So currently the `position` field in `ReturnedTypeDoesNotMatch` just points to the return type annotation. What would be ideal is for that it to **also** contain the positions of the *offending* `return` statements. Getting these positions for these errors would be really simple if they were held on return events. This sort of thing is already implemented for `AssignmentError::DoesNotMeetConstraint`
https://github.com/kaleidawave/ezno/blob/7cf648d5f83d08e9782ac8eb721b181d8aa2427b/checker/src/context/mod.rs#L1390-L1394 so when it emits an error, it also adds a label (additional information) that outlines where the variable type annotation is
 https://github.com/kaleidawave/ezno/blob/7cf648d5f83d08e9782ac8eb721b181d8aa2427b/checker/src/diagnostics.rs#L377-L392

2. and 3. Can't think of any more *metadata* that is needed on `Event` rn, so just a `Span` on each should be fine. I see that [SetsVariable](https://github.com/kaleidawave/ezno/blob/main/checker/src/events/mod.rs#L59) and [Throw](https://github.com/kaleidawave/ezno/blob/main/checker/src/events/mod.rs#L91) are currently the only two unnamed variants, feel free to make the named variants like the others!

I am hoping it shouldn't be too difficult to start on, I am happy to help with any problems that arise if you decide to give it go! **Note: you do not have to fully connect the errors up, I am thinking it might need another change for it to work perfectly.** But if all you could get events setup with a position for each then it would be really useful for now and future ideas!

**Comment by kaleidawave** [comment]
Just a heads up @NitantP. #61 changes the structure of positions a lot so might be worth waiting for that to merge before starting

**Comment by NitantP** [comment]
Understood - thanks, @kaleidawave!

**Comment by kaleidawave** [comment]
Hi @NitantP #61 has been merged. So the repo code should be in a good state to work on this. Some updates:
- The positions should be `source_map::SpanWithSource` (aka have both a position and a file). This is the same as diagnostics/errors so there should be some good examples of creating them
- Since writing the issue I have reworked the return checking. (aka a function annotated as `function x(): number`, check that all returns are subtypes of `number`). Once events have positions, if you want to add the diagnostics you can check out https://github.com/kaleidawave/ezno/blob/88fc8e422fe216b936ca6b223d00492b2bd26f6d/checker/src/events/helpers.rs#L17
Specifically there is a place which would be ideal for using a position here
https://github.com/kaleidawave/ezno/blob/88fc8e422fe216b936ca6b223d00492b2bd26f6d/checker/src/events/helpers.rs#L58

LMK if there are any more questions :)

**Comment by wzwywx** [comment]
Hello, @kaleidawave. I'm trying to solve this issue on my end just to practice my Rust skills (no PR since I presume NitantP is still working on this issue.)

I understand how to modify the diagnostic messages and alter the `ReturnedTypeDoesNotMatch` to have the position for the return location.

But any thoughts on how to get the position of the location the value is returned? 

I can see that `get_return_from_events` iterates through the events, but the pertinent event, `Event::Return` only stores a `&TypeId` and no position for when the event was triggered.

https://github.com/kaleidawave/ezno/blob/88fc8e422fe216b936ca6b223d00492b2bd26f6d/checker/src/events/helpers.rs#L23-L24

**Comment by NitantP** [comment]
Hi @wzwywx - please feel free to submit a PR if you'd like. I haven't been able to make the progress I intended to given circumstances, so you may be in a better position to see this through.

**Comment by kaleidawave** [comment]
@wzwywx awesome! Thanks for attempting it, if you do make any progress (working or not) would be great to put in a PR anyway as I am happy to help finish it if you make a start.

Might be worth reading the title 😅 but yes you have run into the exact problem!

What I would start with is adding a field to the return event variant, (events/mod.ts:68)

```rs
Return { 
  returned: TypeId,
  // \/ field you should add \/
  position: SpanWithSource
}
```

then you will see rust error a bunch and you just have to follow those until it compiles again (so you will probably have to do things like modify `return_value` (context/environment.rs:713) to take a position via a parameter and modify the synthesis code to give that position when it calls that).

Then once you have that field you can go back and get the diagnostic working!

And if you find that okay you can add a position field to **every variant** as I need it for other diagnostics 😀

Also no worries @NitantP

**Comment by wzwywx** [comment]
Yeah, haha I’ve actually read the title, but I underestimated the effort needed to get the return position (which was foolish of me because I was unfamiliar with the API). 

I tried to trace how the current `position` gets its value, and just recently found out it involves more functions than I expected. Still working on that; your tip about the synthesis code might be the thing I’m missing.

Anyhow, thank you for your guidance. I’ll give it another go and see how it goes this time.

21 Oct 2023 at 14:38 by ***@***.***:

**Comment by wzwywx** [comment]
> Hi @wzwywx - please feel free to submit a PR if you'd like. I haven't been able to make the progress I intended to given circumstances, so you may be in a better position to see this through.

Ah, I see. No worries; hopefully your circumstances are improving on your end.
