### ISSUE TITLE
Excess property checks (including the effects of spreads)

### ISSUE THREAD

**Issue by HiperMaximus** [kaleidawave/ezno#42]
It would be nice to allow Ezno to have more guards and checks than Typescript. One of those is performing excess property checks on spreading (which Typescript doesn't do), link to the issue: https://github.com/microsoft/TypeScript/issues/39998

I'm pretty sure there are other common footguns that Typescript has which would be nice to avoid here with a more strict typing. Great work!

**Comment by kaleidawave** [comment]
This is a good suggestion. I haven't implemented excess property checks or spreading into a object yet but when I get around to it I will have a look at catching this!

**Comment by kaleidawave** [comment]
I think this can be implemented here by raising a warning if `expected_type != TypeId::ANY_TYPE` and if the expected type does not have a property (aka the get_property == None)

https://github.com/kaleidawave/ezno/blob/24fb424f668df8fafb3e66ba76850ef6261e4b20/checker/src/synthesis/expressions.rs#L1060-L1069

**Comment by PatrickLaflamme** [comment]
took a look at implementing this. Looks like this approach would result in new excess property warnings in these test cases:

* [Objects Checks](https://github.com/kaleidawave/ezno/blob/main/checker/specification/specification.md#objects-checks)
* [Getters](https://github.com/kaleidawave/ezno/blob/main/checker/specification/specification.md#getters)
* [Assignment](https://github.com/kaleidawave/ezno/blob/main/checker/specification/specification.md#assignment)

In all three cases there is technically an excess property on the assignment, but curious to get your thoughts on whether that's actually what's desired here.

**Comment by kaleidawave** [comment]
Awesome! Thanks for taking a look @PatrickLaflamme 

Yes I understand that [Objects Checks](https://github.com/kaleidawave/ezno/blob/main/checker/specification/specification.md#objects-checks) and [Assignment](https://github.com/kaleidawave/ezno/blob/main/checker/specification/specification.md#assignment) will raise new warnings for excess properties. Once this feature is added you can add a new bullet point to the markdown.

Unsure about the [Getters](https://github.com/kaleidawave/ezno/blob/main/checker/specification/specification.md#getters) one though, I don’t an excess property there? If you have it working then you can put in a draft PR and I may be able to understand that one :)

**Comment by PatrickLaflamme** [comment]
My mistake, it's actually [Generic Extends](https://github.com/kaleidawave/ezno/blob/main/checker/specification/specification.md#generic-extends), not Getters. 

Agree getters would be a concern.
