### ISSUE TITLE
NPM release

### ISSUE THREAD

**Issue by kaleidawave** [kaleidawave/ezno#5]
At the moment the `ezno-cli` is only published on [crates.io](https://crates.io/crates/ezno). Also the publish GitHub action should build a bunch of platform specific binaries and upload them to the [releases page](https://github.com/kaleidawave/ezno/releases). However, as of writing, haven't had a fully successful deploy to verify that works 😆. 

It would be nice, if like similar tools, `ezno-cli` was published as npm executable. This is done with the [bin field in package.json](https://docs.npmjs.com/cli/v9/configuring-npm/package-json?v=true#bin). 

Ideally it would be done by uploading the assets in the release action step.

**The only problem is that these binaries are platform specific. Currently not sure how to communicate the platform the binary is built for to NPM, so that `npx` and `npm install` only install and run the binary for the user's platform.**

Also might need to be in step with the [WASM library code](https://github.com/kaleidawave/ezno/issues/4).

This would be great to get done and tested before the checker gets merged, so that when it is it can be installed from NPM.

**Comment by NoriSte** [comment]
> The only problem is that these binaries are platform specific. Currently not sure how to communicate the platform the binary is built for to NPM, so that `npx` and `npm install` only install and run the binary for the user's platform.

I skimmed through the Cypress package (that have platform-specific binaries) for 5 mins but I didn't found what's their approach 🤔

**Comment by NoriSte** [comment]
> Maybe you could download the binaries afterwards in a script, not sure?

Uhm you're right, I just realized that installing Cypress (the npm dependency, I mean) itself is quick but when you launch it, it installs more things and takes longer...

**Comment by kaleidawave** [comment]
Hmm looking at the ["bin" field docs](https://docs.npmjs.com/cli/v9/configuring-npm/package-json?v=true#bin) it seems NPM is missing something like:
```json
{
  "bin": {
    "myapp:platform=windows": "./cli-windows.exe",
    "myapp:platform=unix": "./cli-unix.exe",
  }
}
```
Would be really nice if something like that was added. It would be the most optimal in terms usability, download and minimal overhead when calling.
### Some other options I can currently think of:
1) Package per platform, with a single specific bin field. Use with `npm install ezno-windows`, not great :/
2) Use the #4 (when it is out). The single WASM version should be work on any platform. Not sure whether could use the CLI setup and error reporting inside wasm (pass flags through), don't want to rewrite and maintain the CLI logic in JS.
3) Some script that downloads a specific binary to a location on first run (which I think is what you have found that Cypress does). May be good if not too difficult and is reliable.

*maybe some other methods?*

**Comment by jasikpark** [comment]
https://github.com/evanw/esbuild probably has the most robust "install the right native dep or use wasm" approach - maybe that's a method to copy

**Comment by kaleidawave** [comment]
WASM looks the best way to go. Just played around and managed to get `argh` (the cli argument parsing framework ezno-cli current uses) to work in WASM. Requires injecting a file to pass over arguments but that should be fine.
```rust
#[wasm_bindgen(raw_module = "./get_args")]
extern {
    #[wasm_bindgen]
    fn get_args() -> String;
}

#[wasm_bindgen(start)]
fn main() {
    let get_args = get_args();
    let arguments = get_args.split('\0').collect::<Vec<_>>();

    match FromArgs::from_args(&["ezno-cli"], &arguments) {
        Ok(TopLevel { nested }) => {
            todo!()
        }
        Err(err) => {
            log(&err.output);
        }
    } 
}
```
Can work on this at the same time as #4

**Comment by jasikpark** [comment]
ezno-lsp when 👀

**Comment by kaleidawave** [comment]
haha yeah will probably make public the same time as the checker. once I have a got a few things in place (like this issue) and then find the time to clear up my current checker code then will make that public.

**Comment by kaleidawave** [comment]
This is now implemented as well as automated deploys. Package @ https://www.npmjs.com/package/ezno

It uses the WASM version (option 2) which seems the simplest and least effort. Maybe at some point could have an additional `--native` flag and review option 3.
