### ISSUE TITLE
Read from imports

### ISSUE THREAD

**Issue by kaleidawave** [kaleidawave/ezno#63]
Imports are not currently implemented :/

They should read from the **JavaScript** source 99% of the time (Ezno has some problems with existing `.d.ts` files, JS is a better source of truth). 

To do
- Think about how import resolving works (look at whether there is an existing library that can do this for us)
- Have a `Module` struct that contains information (I think there is one from my previous attempt, which needs improving)
- Think about the side-effects of module important
- Record things around `export` declarations
- Dynamic import?

**Comment by kaleidawave** [comment]
Marking this as 90% completed by #71. Separate issues are:
- Name lookup, needs `package.json` and `node_modules` reading. Also want to support Deno packages here (not sure how they work tho)
- Dynamic / expression level `import`. Will have to rule out some cases when the import is too dynamic

**Comment by chengyuhui** [comment]
Is it possible to further abstract this (for example, with a `ModuleResolver` trait) so that it is possible to use projects like `oxc-resolver` to handle `package.json` and `node_modules`?

```rust
trait ModuleResolver {
  // `path` is the full path to the file that is trying to import `spec`.
  fn resolve<P: AsRef<Path>>(&self, path: P, spec: &str) -> Result<(Path, String)>;
}
```

**Comment by kaleidawave** [comment]
Yep current there is the [`ReadFromFS`](https://docs.rs/ezno-checker/latest/ezno_checker/trait.ReadFromFS.html) trait that is `Path -> String`. At the moment only relative path imports are supported. [The resolving for that (aka joining relative parts) is done internally in the checker](https://github.com/kaleidawave/ezno/blob/182dc1f031d26860c52c70b25cdf02bfbdc5941f/checker/src/lib.rs#L316-L319). 

When I get to adding external package support (which needs more things to work first) I think I will add `oxc-resolver` internally and extend that logic using `oxc-resolver`s resolving algorithm.

Maybe I that should be independent of `ezno-checker` and so it should be done in the CLI instead (for example is `package.json` parsing part of the JavaScript specification, is it different for Deno etc)? Not sure yet...

--- 
For commonjs, I think `require` could be implemented as a [*constant function*](https://github.com/kaleidawave/ezno/blob/main/checker/src/behavior/constant_functions.rs), which is a custom piece of Rust code that can do internal things that aren't possible (or very difficult) to represent in the type system. So as long as it isn't a dynamic path (which breaks everything) it should eventually be possible

**Comment by chengyuhui** [comment]
If my understanding of the status of this project is correct, we shouldn't expect Ezno to be able to read some random npm package anyway (I have read somewhere that we also have issues reading `.d.ts` files?).

I'll try to see if I can blindly plug in `oxc-resolve` locally, but it probably will not work...

**Comment by kaleidawave** [comment]
Hmm, I need to think about it. What I currently know:
- The `ReadFromFS` trait is only for enabling both native bindings (`std::fs::read_to_string`) and WASM bindings (passed as `js_sys::Function`). **Maybe it could be changed** so that the *resolving* is the job of the code that uses the [`ezno_checker::check_project`](https://docs.rs/ezno-checker/latest/ezno_checker/fn.check_project.html) function, rather than inside of the checker
- For Ezno to check a `.js` file that has been *built* (aka downloaded for a package manager), then it needs both the JS file and it's `.d.ts`, it then needs to check the JS (because that is the source of truth and contains event and other dependent information) and **zip** with the items in the definition file (to provide parameter constraints, interfaces and type aliases etc). In the future it is possible to cache this, so if this sounds slow, don't worry 😆 this is only on cold *start*. I haven't tried `oxc-resolve` yet but it should be able to return both contents for a code file and a definition file for a import path?

[While promises and other things not implemented](https://github.com/kaleidawave/ezno/blob/main/checker/specification/to_implement.md), I have been putting importing NPM packages off..

Should probably open a separate issue for importing NPM and other packages

**Comment by chengyuhui** [comment]
>  I haven't tried `oxc-resolve` yet but it should be able to return both contents for a code file and a definition file for a import path?

It actually doesn't, since the functionality of that crate mirrors Webpack's `enhanced-resolve`, and both `oxc` and `webpack` do not do type checking by default, and therefore do not need to deal with `.d.ts` files (it's the job of `tsc`).
