### ISSUE TITLE
Improve CI testing and publishing

### ISSUE THREAD

**Issue by kaleidawave** [kaleidawave/ezno#7]
### Testing
- **Run fuzzing tests in parallel**. Will show red light correctly and be faster
- Get cargo fuzz from: https://github.com/rust-fuzz/cargo-fuzz/releases/tag/0.11.2
- Split up testing step by crates (eventually this should mean that it should only run tests for crates that have changed)
- Have some sort of feature matrix for testing
- **Add hyperfine and flamegraph** performance tracing
- Enforce Cargo.toml formats

*need to check whether caching is working correctly*

### Publishing
- Automatically add `ezno-ast-generator` if `ezno-parser` is updated

**Comment by jasikpark** [comment]
https://github.com/marketplace/actions/brndnmtthws-rust-action-cargo-binstall / https://github.com/brndnmtthws/rust-action perhaps?
