### ISSUE TITLE
Parse error with comment in object literal

### ISSUE THREAD

**Issue by coderaiser** [kaleidawave/ezno#96]
Strange error for [this code](https://github.com/coderaiser/supertape/blob/v9.0.0/packages/supertape/test/errors.ts#L61):

![image](https://github.com/kaleidawave/ezno/assets/1573141/8d34ca75-3d86-4532-a55f-22d52bd32f0f)

**Comment by kaleidawave** [comment]
Looks like a parser bug.

Comments are tokenised and then *some* should be stored in the AST for hover information etc.

I think your example, is something like

```ts
class X {
    // comment 1
    // comment 2
    x() {}
}
```

I think at moment there are two problems:
- Comments other than ones that are `/** ... */` are attempted to be stored in the AST (it should skip over `//` some of the time) 
- It currently works using [`WithComment<PropertyKey>`](https://docs.rs/ezno-parser/latest/ezno_parser/enum.WithComment.html), which expects one comment. The parsing for it should collapse multiple comments into one

Will take a look when I have some free time. Or expose the option where the parser skips comments

**Comment by kaleidawave** [comment]
Given a few lines below there is a `async` function, which it currently doesn't work in Ezno. It might be a while before you can check that file.
